name: tts
description: >
  This example shows how to implement text to speech, i.e., speech synthesis,
  using sherpa-onnx.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.10.30

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  path: ^1.9.0
  sherpa_onnx: ^1.10.30
  # sherpa_onnx:
  #   path: ../../flutter/sherpa_onnx
  url_launcher: 6.2.6
  url_launcher_linux: 3.1.0
  audioplayers: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vits-mimic3-fa-haaniye_low/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/aav/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/art/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/azc/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/bat/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/bnt/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/ccs/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/cel/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/cus/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/dra/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/esx/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/gmq/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/gmw/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/grk/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/inc/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/ine/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/ira/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/iro/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/itc/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/jpx/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/map/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/miz/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/myn/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/poz/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/roa/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/sai/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/sem/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/sit/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/tai/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/trk/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/urj/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/zle/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/zls/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/lang/zlw/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/voices/
    - assets/vits-mimic3-fa-haaniye_low/espeak-ng-data/voices/!v/
    - assets/vits-piper-en_US-libritts_r-medium/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/aav/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/art/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/azc/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/bat/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/bnt/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/ccs/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/cel/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/cus/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/dra/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/esx/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/gmq/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/gmw/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/grk/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/inc/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/ine/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/ira/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/iro/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/itc/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/jpx/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/map/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/miz/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/myn/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/poz/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/roa/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/sai/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/sem/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/sit/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/tai/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/trk/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/urj/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/zle/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/zls/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/zlw/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/voices/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/voices/!v/
